### ISSUE TITLE
Uncaught Error: cannot find module "./shaders/link.vert.js"

### ISSUE THREAD

**Issue by security-database** [ayasdi/grapher#18]
Hello
Fetch GitHub repo and try all exemples (1.1.0)

grapher.js:28 : 
Uncaught Error: cannot find module "./shaders/link.vert.js"

Do i miss something ?

**Comment by cixzhang** [comment]
Hi,

When did you encounter this error? Was this during a build or when importing?

**Comment by security-database** [comment]
Hello,

Just clone the repo and try the examples (like 1-simple.html)
Worked with older version.

**Comment by cixzhang** [comment]
Thanks!

This should be fixed on the latest master (1.1.2).
