### ISSUE TITLE
How are nodes rendered with WebGL?

### ISSUE THREAD

**Issue by CoDEmanX** [ayasdi/grapher#21]
I starred at your highly interesting code for a while now, but can't explain how it manages to draw circles using the gl renderer. There are properties like position, radius and resolution in the node vertex shader, but it doesn't calculate the points for a circle there.

The renderNodes function uses TRIANGLES, so there must be some other code. updateNodesBuffer seems to calculate some extra coordinates, but I can't see it calculating points based on the resolution.

Can you explain how it achieves to render perfect circles?

**Comment by cixzhang** [comment]
Hi,

We create triangles slightly larger than the circle, then use the node fragment shader to color in the pixels in a circle. @DianaSuvorova wrote a post about this some time ago that explains this in detail: http://engineering.ayasdi.com/2015/05/02/how-to-draw-a-filled-circle-in-webgl/

Hope that helps!
