### ISSUE TITLE
Not compatible with webpack when it comes to require shaders

### ISSUE THREAD

**Issue by dgarciap** [ayasdi/grapher#25]
Hello,
I've got a problem when using this library with webpack. 

When using browserify you can use the extension browserify-shader and it gives you what seems a function, which returns a string containing a shader.

In the case of webpack, using the extension webpack-glsl-loader or glslify-loader, it returns an string.

So when executing `renderer.js:line 39 - method getShaders`. It throws an error because this method is executing `source()` and in webpack it should execute `source`.

To fix this it is needed checking the type -> `typeof source == "string"` and executing `source` or `source()` accordingly.

**Comment by cixzhang** [comment]
Hi,

The ```getShaders``` method inside of ```gl/renderer.js``` requires that the source is a string not a function. If webpack returns a string, then this should already work as is. On current master, our shaders are also encoded as javascript strings.

I'd like to get a bit of insight into your use case. Are you trying to package Grapher with other source code using webpack or browserify? Are you using a custom shader and passing it in? Maybe you can try #24 and see if that helps you?

**Comment by dgarciap** [comment]
Sorry, I drew the wrong conclusion.

Right now, I'm using webpack and it works as expected. It is when you use browserify with browserify-shader. If you request a shader, It gives you a method you must invoque to get this shader. So the format here is different. 

` gl.shaderSource(shader, vs()); `
[Example](https://www.npmjs.com/package/browserify-shader)

But with webpack and webpack-glsl-loader It is working perfectly fine. :)

**Comment by cixzhang** [comment]
Glad to hear it's working with webpack :)

When you say you're using browserify with browserify-shader, is it our default shaders that are failing on that line? Currently our shaders are javascript files. For example in  https://github.com/ayasdi/grapher/blob/master/modules/renderers/gl/shaders/link.frag.js we are exporting a javascript string rather than the shader source. I'm unsure why browserify-shader would try to transform these files.

**Comment by cixzhang** [comment]
I think this should be resolved now. :) We've updating how we package in #32.
