### ISSUE TITLE
grapher.off() doesn't work

### ISSUE THREAD

**Issue by danpaulsmith** [ayasdi/grapher#5]
http://jsbin.com/qeqelabize/1/edit?js,console,output

**Comment by dannycochran** [comment]
nice catch. right now it only works if you can specify the original function. e.g.:

```javascript
var onMouseDown = function (e) { console.log(e, 'on mouse down'); };
grapher.on('mousedown', onMouseDown);
grapher.off('mousedown', onMouseDown);
```

but I suppose there's times when you just want to remove all listeners of a type.

https://github.com/ayasdi/grapher/pull/7

**Comment by danpaulsmith** [comment]
Ah right, suppose that’s normal then! Think I was just following one of the examples :)

**Comment by cixzhang** [comment]
Merged
