### ISSUE TITLE
clear/reset canvas

### ISSUE THREAD

**Issue by danpaulsmith** [ayasdi/grapher#8]
Hey, how would you suggest I clear or wipe the canvas? I can't see anything obvious in grapher's interface. I want to switch between graphs as well as loading data into an existing graph. Thanks. And sorry this isn't really an issue, would you prefer this on StackOverflow with a #grapher ?

**Comment by dannycochran** [comment]
you should just be able to do:

```javascript
grapher.data({nodes: [], links: []}).update().render();
```

but it looks like that only propagates when you resize the page. that's a bug on our part. in the interim you can force clear by doing this:

```javascript
// clear grapher
grapher.data({nodes: [], links: []}).update().render();
var gl = grapher.canvas._getWebGL();
gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);

// re-render with new data
grapher.data(newData).update().render();
```

**Comment by danpaulsmith** [comment]
Yep, thanks!
